const destinations = [
    {
        id: 1,
        name: "Bali, Indonesia",
        continent: "Asia",
        description: "Tropical paradise with beaches and temples",
        image: "assets/images/Bali.jpg",
        minBudgetDay: 40,
    },
    {
        id: 2,
        name: "Paris, France",
        continent: "Europe",
        description: "The city of love, iconic landmarks and heart of France",
        image: "assets/images/paris.jpg",
        minBudgetDay: 125,
    },
    {
        id: 3,
        name: "Cairo, Egypt",
        continent: "Africa",
        description: "Ancient wonders, rich history and special culture",
        image: "assets/images/Caire.jpg",
        minBudgetDay: 50,
    },
    {
        id: 4,
        name: "New York, USA",
        continent: "North America",
        description: "The city that never sleeps and make dreams come true",
        image: "assets/images/newYork.jpg",
        minBudgetDay: 250,
    },
    {
        id: 5,
        name: "Tokyo, Japan",
        continent: "Asia",
        description: "Modern metropolis with ancient traditions",
        image: "assets/images/Tokyo.jpg",
        minBudgetDay: 150,
    },
    {
        id: 6,
        name: "Barcelona, Spain",
        continent: "Europe",
        description: "Gaudi architecture and Mediterranean beaches",
        image: "assets/images/barcelone.jpg",
        minBudgetDay: 180,
    },
    {
        id: 7,
        name: "Dubai, UAE",
        continent: "Asia",
        description: "Luxury shopping and desert adventures",
        image: "assets/images/dubai.jpg",
        minBudgetDay: 300,
    },
    {
        id: 8,
        name: "Rio de Janeiro, Brazil",
        continent: "South America",
        description: "Vibrant culture and beautiful landscapes",
        image: "assets/images/Rio.jpg",
        minBudgetDay: 90,
    },
    {
        id: 9,
        name: "Bangkok, Thailand",
        continent: "Asia",
        description: "Street food paradise and bustling temples",
        image: "assets/images/bangkok.jpg",
        minBudgetDay: 40,
    },
    {
        id: 10,
        name: "Rome, Italy",
        continent: "Europe",
        description: "Ancient history, delicious cuisine and attractive architecture",
        image: "assets/images/Rome.jpg",
        minBudgetDay: 110,
    },
    {
        id: 11,
        name: "Sydney, Australia",
        continent: "Oceania",
        description: "Stunning beaches and iconic landmarks",
        image: "assets/images/Bali.jpg",
        minBudgetDay: 300,
    },
    {
        id: 12,
        name: "Amsterdam, Netherlands",
        continent: "Europe",
        description: "Charming canals, vibrant culture and heart of Netherlands",
        image: "assets/images/amesterdam.jpg",
        minBudgetDay: 150,
    },
    {
        id: 13,
        name: "Marrakech, Morocco",
        continent: "Africa",
        description: "Exotic markets, desert landscapes and heart of Morocco",
        image: "assets/images/marrakech.jpg",
        minBudgetDay: 50,
    },
    {
        id: 14,
        name: "Istanbul, Turkey",
        continent: "Asia",
        description: "Where Europe meets Asia with rich history",
        image: "assets/images/istanbul.jpg",
        minBudgetDay: 80,
    },
    {
        id: 15,
        name: "Reykjavik, Iceland",
        continent: "Europe",
        description: "Waterfalls, glaciers, northern lights and heart of Iceland",
        image: "assets/images/iceland.jpg",
        minBudgetDay: 100,
    },
    {
        id: 16,
        name: "Santorini, Greece",
        continent: "Europe",
        description: "The beauty of seas merged with white buildings",
        image: "assets/images/santorini.jpg",
        minBudgetDay: 140,
    },
    {
        id: 17,
        name: "Sidi Bousaid, Tunisia",
        continent: "Africa",
        description: "The beauty of seas merged with white buildings",
        image: "assets/images/Tunis.jpg",
        minBudgetDay: 140,
    }
];
